server:
  port: 7070
  servlet:
    context-path: /server

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
    user:
      name: "admin"
      password: "admin"

swagger:
  enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  appName: actuator-server
  author: lyscharlie