server:
  port: 7070
  servlet:
    context-path: /server
  forward-headers-strategy: native # 解决nginx代理导致的异常

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: admin
      password: admin

swagger:
  enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  appName: actuator-server
  author: lyscharlie